### ISSUE TITLE
MegaM@Rt: integrating JTL with MegaM@Rt platform, based on Eclipse Modeling 2018-09

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [MDEGroup/jtl-eclipse#1]
Cioa,
I've started the integration of MegaM@Rt tools within the common MegaM@Rt platform, based on Eclipse Modelling 2018-09.
According to [JTL documentation](https://github.com/MDEGroup/jtl-eclipse/blob/master/README.md) JTL seems to be only available as RCP (JTL Eclipse Product), but not as a number of features/plugins that could be installed from an update site (or Marketplace) in an existing compatible Eclipse instance. Is that correct?
MegaM@Rt is expecting that most of Eclipse-based tools can be installed as plugins from an update site. Could this be possible for JTL? Otherwise, JTL cannot be integrated, so it will only work standalone, as an Eclipse RCP.
Please, comment on this, so we can explorer integration approaches for JTL within the common MegaM@Rt Eclipse platform.

In case JTL could be released as a number of features/plugins:
- Are they compatible (or could they make compatible) with Eclipse Modeling 2018-09?
- Are those features/plugins identified and available withing an update site or could that update site be built?

Grazie mille.
Yosu

**Comment by mtucci** [comment]
Hi,
JTL is also available as a set of plugins. I updated the [update site](https://github.com/MDEGroup/jtl-eclipse-update-site/raw/master/) to work on Eclipse Modeling 2018-09.
I also modified the [README](https://github.com/MDEGroup/jtl-eclipse/blob/master/README.md) accordingly.

Thank you for noticing this issue.
Michele

**Comment by jesus-gorronogoitia** [comment]
HI @mtucci 
The update site you refer to in your comment, but also in the README is broken (HTTP 404 Not found). Please, provide me the valid update site link and update the README  accordingly. Grazie mille. Yosu

**Comment by mtucci** [comment]
Hi,
Github does not serve directory listings. That is why you get the 404.
Please, try to use it as an update site in Eclipse Modeling. It should work just fine.

Thank you.
Michele

**Comment by jesus-gorronogoitia** [comment]
Hi @mtucci grazie. I will try it out asap. I will let you know.

**Comment by jesus-gorronogoitia** [comment]
Hi @mtucci the update site works well. I could install JTL. Now I will integrate it in the common MegaM@Rt update site.
