### ISSUE TITLE
New JTL 0.3.0 depends on plugin org.apache.logging.log4j.api, which is not available

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [MDEGroup/jtl-eclipse#2]
Hi @mtucci 
I've relized that the new JTL version existing on the update site, v0.3.0 requires the plugin:
org.apache.logging.log4j.api which I can't find in several Eclipse repositories, including Orbit.
`Your original request has been modified.
  "JTL - Janus Transformation Language" is already installed, so an update will be performed instead.
Cannot complete the install because one or more required items could not be found.
  Software being installed: JTL - Janus Transformation Language 0.3.0.201901111448 (it.univaq.jtl.feature.feature.group 0.3.0.201901111448)
  Missing requirement: JTL ATL Transformation Runtime Plug-in 0.3.0.201901111448 (JTL.atl 0.3.0.201901111448) requires 'osgi.bundle; org.apache.logging.log4j.api 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: JTL - Janus Transformation Language 0.3.0.201901111448 (it.univaq.jtl.feature.feature.group 0.3.0.201901111448)
    To: org.eclipse.equinox.p2.iu; JTL.atl [0.3.0.201901111448,0.3.0.201901111448]`
Where should I install this plugin from?
In my Eclipse IDE I have other versions of Log4j installed:
- Eclipse Orbit Apache Jakarta log4j Plug-in, 1.2.15.v201012070815
- Eclipse.org SLF4J LOG4J-12 Binding, 1.7.2.v20131105-2200
Grazie mille
Yosu

**Comment by jesus-gorronogoitia** [comment]
I also have installed from Orbit other Apache Commons Logging plugins (but not the one required by JTL):
- Apache Commons Logging Plug-in, 1.1.1v201101211721
- Apache Commons Logging, 1.2.0.v20180409-1502
So, As you can see, there are many Apache Commons Logging and Log4j plugins available, but not the ones required by JTL. What is the update site from where I can install it?

**Comment by mtucci** [comment]
Hi @jesus-gorronogoitia,
I committed a fixed version where missing dependencies are included in the JTL feature.
JTL uses Log4J 2 which is not available in any update site I know of.
Thank you for noticing this.

**Comment by jesus-gorronogoitia** [comment]
Grazie mille @mtucci 
Your fix works, so I could install JTL 0.3.0.
