### ISSUE TITLE
Problem at runing transformation

### ISSUE THREAD

**Issue by DebianRDT** [MDEGroup/jtl-eclipse#3]
Hello,

When I download any version of JTL and try to use the transformations of the examples in Ubuntu 18.04 and Ubuntu 19.04 I get the following error:

JASPWrapper 0.9 - Command executing...
/bin/sh -c  LD_LIBRARY_PATH=/home/debian/Descargas/JTL-0.2.0.201801301648-linux.gtk.x86_64/JTL/plugins/JTL_0.2.0.201801301648/lib /home/debian/Descargas/JTL-0.2.0.201801301648-linux.gtk.x86_64/JTL/plugins/JTL_0.2.0.201801301648/lib/dl-complex.linux.20110713.static.beta  /home/debian/Descargas/JTL-0.2.0.201801301648-linux.gtk.x86_64/JTL/workspace/HSM2SM/transformations/hsm2sm.dl  
--------------------- 
/bin/sh: /home/debian/Descargas/JTL-0.2.0.201801301648-linux.gtk.x86_64/JTL/plugins/JTL_0.2.0.201801301648/lib/dl-complex.linux.20110713.static.beta: No existe el archivo o el directorio

This is my Java:

openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.19.04.2-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)

The file is in the path and when I launch the command by hand it doesn't give me any kind of error that it doesn't exist...
This error doesn't happen to a colleague and we can't understand why it works for him and not for me. JTL is an important part of my research project and I've been stuck here for several days.

**Comment by mtucci** [comment]
Hi,
thank you for reporting this.

Could you please try running the same transformation using the [latest version](https://github.com/MDEGroup/jtl-eclipse/releases/tag/v0.3.0.2019)?
Is the error you get exactly the same?

Your Java version is fine.

**Comment by DebianRDT** [comment]
Hi,

Same error :(

JASPWrapper 0.9 - Command executing...
/bin/sh -c  LD_LIBRARY_PATH=/home/debian/Descargas/JTL-0.3.0.201901111448-linux.gtk.x86_64/JTL/plugins/JTL_0.3.0.201901111448/lib /home/debian/Descargas/JTL-0.3.0.201901111448-linux.gtk.x86_64/JTL/plugins/JTL_0.3.0.201901111448/lib/dl-complex.linux.20110713.static.beta  /home/debian/Descargas/JTL-0.3.0.201901111448-linux.gtk.x86_64/JTL/workspace/HSM2SM/transformations/hsm2sm.dl  
--------------------- 
/bin/sh: /home/debian/Descargas/JTL-0.3.0.201901111448-linux.gtk.x86_64/JTL/plugins/JTL_0.3.0.201901111448/lib/dl-complex.linux.20110713.static.beta: No existe el archivo o el directorio

**Comment by DebianRDT** [comment]
And the file exists...

debian@debian-VirtualBox:~/Descargas/JTL-0.3.0.201901111448-linux.gtk.x86_64/JTL/plugins/JTL_0.3.0.201901111448/lib$ ls
dl-complex.linux.20110713.static.beta  libltdl.so.3

**Comment by mtucci** [comment]
The issue is caused by the `dl-complex.linux.20110713.static.beta` executable being a 32bit binary.

One can get the error "no such file or directory" when trying to run a 32bit binary on a 64bit system that doesn't have 32bit support installed, even if the file is there.
Unfortunately, the authors of dlv-complex (the solver JTL uses) only distribute it as a 32bit binary.

On Ubuntu, you could install the 32bit support:
```bash
sudo dpkg --add-architecture i386
sudo apt update
sudo apt install libc6:i386 libstdc++6:i386
```

**Comment by DebianRDT** [comment]
It works!!

Thank you :)
